# Generated by Django 3.2.19 on 2023-05-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_user_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='black_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification',
            field=models.CharField(choices=[('me', 'Мне'), ('me_and_agent', 'Мне и агенту'), ('agent', 'Агенту'), ('off', 'Отключить')], default='me', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('manager', 'Менеджер'), ('user', 'Юзер'), ('owner', 'Застроищик')], default='user', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='to_agent',
            field=models.BooleanField(default=False),
        ),
    ]
