# Generated by Django 3.2.19 on 2023-05-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_blacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedToken',
        ),
    ]
