# Generated by Django 3.2.19 on 2023-05-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0003_alter_news_date'),
        ('user_app', '0006_delete_blacklistedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_apartments',
            field=models.ManyToManyField(blank=True, to='infrastructures_app.Apartment', verbose_name='Пользователи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_infrastructures',
            field=models.ManyToManyField(blank=True, to='infrastructures_app.Infrastructure', verbose_name='Пользователи'),
        ),
    ]
