# Generated by Django 3.2.19 on 2023-06-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(upload_to='img/avatar/', verbose_name='Аватар'),
        ),
    ]
