# Generated by Django 3.2.19 on 2023-06-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='paid_by',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
