# Generated by Django 3.2.19 on 2023-06-16 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0022_remove_image_image_delete'),
        ('user_app', '0013_alter_subscription_paid_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infrastructure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructures_app.infrastructure')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_favorite_infrastructure',
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructures_app.apartment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_favorite_apartment',
            },
        ),
    ]
