# Generated by Django 3.2.19 on 2023-06-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructures_app', '0001_initial'),
        ('checkerboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riser',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructures_app.section'),
        ),
        migrations.AddField(
            model_name='floor',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructures_app.section'),
        ),
        migrations.AddField(
            model_name='checkerboard',
            name='infrastructure_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='infrastructures_app.infrastructure'),
        ),
    ]
