# Generated by Django 3.2.19 on 2023-06-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0008_infrastructure_photo'),
        ('checkerboard_app', '0003_alter_checherboard_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checherboard',
            new_name='Checkerboard',
        ),
    ]
