# Generated by Django 3.2.19 on 2023-06-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_view', models.CharField(choices=[('secondary', 'Вторичное жилье'), ('primary', 'Новострой'), ('cottage', 'Коттедж'), ('all', 'Все')], default='all', max_length=20, verbose_name='Вид')),
                ('filter_status', models.CharField(choices=[('rented', 'Сдан'), ('vacant', 'Не сдан')], default='rented', max_length=20, verbose_name='Статус')),
                ('filter_district', models.CharField(max_length=100, verbose_name='Район')),
                ('filter_microdistrict', models.CharField(max_length=100, verbose_name='Микрорайон')),
                ('filter_quantity', models.CharField(choices=[('1', '1-комнатная'), ('2', '2-комнатная'), ('3', '3-комнатная'), ('4', '4-комнатная')], default='1', max_length=20, verbose_name='Количество комнат')),
                ('filter_price_from', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена от')),
                ('filter_price_to', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена до')),
                ('filter_area_from', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь от')),
                ('filter_area_to', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь до')),
                ('filter_purpose', models.CharField(choices=[('apart', 'Квартира'), ('house', 'Дом')], default='apart', max_length=20, verbose_name='Статус')),
                ('filter_payment', models.CharField(blank=True, choices=[('cash', 'Наличные'), ('maternity', 'Мат. капитал'), ('mortgage', 'Ипотека'), ('military', 'Военная ипотека'), ('not', 'Неважно')], max_length=20, verbose_name='Варианты расчета')),
                ('filter_state', models.CharField(choices=[('need', 'Требует ремонта'), ('building', 'Ремонт от строителей')], default='building', max_length=20, verbose_name='Жилое состояние')),
            ],
        ),
    ]
