# Generated by Django 3.2.19 on 2023-05-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='payment',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('maternity', 'Мат. капитал'), ('mortgage', 'Ипотека'), ('military', 'Военная ипотека'), ('not', 'Неважно')], max_length=20, verbose_name='Варианты расчета'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='purpose',
            field=models.CharField(choices=[('apart', 'Квартира'), ('house', 'Дом')], default='apart', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='quantity',
            field=models.CharField(choices=[('1', '1-комнатная'), ('2', '2-комнатная'), ('3', '3-комнатная'), ('4', '4-комнатная')], default='1', max_length=20, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='state',
            field=models.CharField(choices=[('need', 'Требует ремонта'), ('building', 'Ремонт от строителей')], default='building', max_length=20, verbose_name='Жилое состояние'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='status',
            field=models.CharField(choices=[('rented', 'Сдан'), ('vacant', 'Не сдан')], default='rented', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='view',
            field=models.CharField(choices=[('secondary', 'Вторичное жилье'), ('primary', 'Новострой'), ('cottage', 'Коттедж'), ('all', 'Все')], default='all', max_length=20, verbose_name='Вид'),
        ),
    ]
