# Generated by Django 3.2.19 on 2023-06-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters_app', '0003_auto_20230528_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='area_from',
            new_name='filter_area_from',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='area_to',
            new_name='filter_area_to',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='district',
            new_name='filter_district',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='microdistrict',
            new_name='filter_microdistrict',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='payment',
            new_name='filter_payment',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='price_from',
            new_name='filter_price_from',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='price_to',
            new_name='filter_price_to',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='purpose',
            new_name='filter_purpose',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='quantity',
            new_name='filter_quantity',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='state',
            new_name='filter_state',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='status',
            new_name='filter_status',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='view',
            new_name='filter_view',
        ),
    ]
