# Generated by Django 3.2.19 on 2023-06-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(choices=[('secondary', 'Вторичное жилье'), ('primary', 'Новострой'), ('cottage', 'Коттедж')], default='primary', max_length=20, verbose_name='Вид')),
                ('technology', models.CharField(choices=[('panel', 'Панельный'), ('monolith', 'Монолит')], default='panel', max_length=20, verbose_name='Технология')),
                ('apart_status', models.CharField(choices=[('rented', 'Сдан'), ('vacant', 'Не сдан')], default='rented', max_length=20, verbose_name='Статус')),
                ('quantity', models.CharField(choices=[('1', '1-комнатная'), ('2', '2-комнатная'), ('3', '3-комнатная'), ('4', '4-комнатная')], default='1', max_length=20, verbose_name='Количество комнат')),
                ('appointment', models.CharField(choices=[('Residential', 'Жилая'), ('Commercial', 'Коммерческая'), ('Industrial', 'Промышленная')], default='Residential', max_length=20, verbose_name='Вид')),
                ('state', models.CharField(choices=[('need', 'Требует ремонта'), ('building', 'Ремонт от строителей')], default='building', max_length=30, verbose_name='Жилое состояние')),
                ('plane', models.CharField(choices=[('studio', 'Студия'), ('standart', 'Стандарт'), ('open', 'Свободная'), ('penthouse', 'Пентхаус')], default='open', max_length=20, verbose_name='Планировка')),
                ('area', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Площадь')),
                ('kitchen_area', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Площадь кухни')),
                ('balcony', models.CharField(choices=[('yes', 'Да'), ('not', 'Нет')], default='yes', max_length=20, verbose_name='Планировка')),
                ('heating', models.CharField(choices=[('electro_heating', 'Электрическое'), ('gas_heating', 'Газовое')], default='yes', max_length=20, verbose_name='Газ')),
                ('payment', models.CharField(blank=True, choices=[('cash', 'Наличные'), ('maternity', 'Мат. капитал'), ('mortgage', 'Ипотека'), ('military', 'Военная ипотека'), ('not', 'Неважно')], max_length=20, verbose_name='Варианты расчета')),
                ('commission', models.DecimalField(decimal_places=1, max_digits=10, null=True, verbose_name='Коммисия агенту')),
                ('communication', models.CharField(choices=[('call', 'Звонок'), ('message', 'Сообщение'), ('two', 'Звонок+Сообщение')], default='call', max_length=20, verbose_name='Способ связи')),
                ('apart_description', models.TextField(max_length=400, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('schema', models.ImageField(upload_to='img/schema/', verbose_name='Схема')),
                ('accept', models.BooleanField(default=False, verbose_name='Одобренно')),
                ('rejection', models.CharField(choices=[('foto', 'Фото'), ('price', 'Цена'), ('description', 'Описание')], default='', max_length=20, verbose_name='Причины отклонения')),
            ],
        ),
        migrations.CreateModel(
            name='Corp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=0, default=1, max_digits=3, verbose_name='Корпус номер')),
            ],
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file/docs/', verbose_name='Документы')),
                ('is_excel', models.BooleanField(default=False, verbose_name='Ексель')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_place', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='img/image/')),
                ('hash', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageApart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_place', models.IntegerField(null=True)),
                ('image', models.ImageField(upload_to='img/image/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='Главное фото')),
                ('address', models.CharField(max_length=64, null=True, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('apart', 'Квартира'), ('house', 'Дом')], default='apart', max_length=20, verbose_name='Статус')),
                ('view', models.CharField(choices=[('multifamily', 'многоквартирный'), ('singlefamily', 'одноквартирный')], default='singlefamily', max_length=20, verbose_name='Тип')),
                ('technology', models.CharField(choices=[('panel', 'Панельный'), ('monolith', 'Монолит')], default='panel', max_length=20, verbose_name='Технология')),
                ('territory', models.CharField(choices=[('close', 'Закрытая'), ('open', 'Открытая')], default='close', max_length=20, verbose_name='Территория')),
                ('distance', models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Дистанция')),
                ('celling_height', models.DecimalField(decimal_places=1, max_digits=10, null=True, verbose_name='Высота потолков')),
                ('electricity', models.CharField(choices=[('yes', 'Подключено'), ('not', 'Отключено')], default='yes', max_length=20, verbose_name='Электричество')),
                ('gas', models.CharField(choices=[('yes', 'Есть'), ('not', 'Нет')], default='yes', max_length=20, verbose_name='Газ')),
                ('heating', models.CharField(choices=[('central', 'Центрайльное'), ('individual', 'Индивидуальное')], default='central', max_length=20, verbose_name='Отопление')),
                ('sewage', models.CharField(choices=[('central', 'Центрайльное'), ('individual', 'Индивидуальное')], default='central', max_length=20, verbose_name='Каннализация')),
                ('watter_supply', models.CharField(choices=[('central', 'Центрайльное'), ('individual', 'Индивидуальное')], default='central', max_length=20, verbose_name='Водоснабжение')),
                ('map', models.TextField(blank=True, null=True, verbose_name='Карта')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=0, default=1, max_digits=3, verbose_name='Секция номер')),
                ('corp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructures_app.corp')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('news_description', models.TextField(max_length=600, verbose_name='')),
                ('infrastructure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructures_app.infrastructure')),
            ],
        ),
    ]
