# Generated by Django 3.2.19 on 2023-06-19 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkerboard_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotion_app', '0001_initial'),
        ('infrastructures_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imageapart',
            name='apartment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageApart', to='infrastructures_app.apartment'),
        ),
        migrations.AddField(
            model_name='image',
            name='infrastructure_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageInfrastructure', to='infrastructures_app.infrastructure'),
        ),
        migrations.AddField(
            model_name='docs',
            name='infrastructure_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructures_app.infrastructure'),
        ),
        migrations.AddField(
            model_name='corp',
            name='infrastructure_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructures_app.infrastructure'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkerboard_app.floor'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='infrastructure_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructures_app.infrastructure'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='promotion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='promotion_app.promotion'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='riser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkerboard_app.riser'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
