# Generated by Django 3.2.19 on 2023-05-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='appointment',
            field=models.CharField(choices=[('Residential', 'Жилая'), ('Commercial', 'Коммерческая'), ('Industrial', 'Промышленная')], default='Residential', max_length=20, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='balcony',
            field=models.CharField(choices=[('yes', 'Да'), ('not', 'Нет')], default='yes', max_length=20, verbose_name='Планировка'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='communication',
            field=models.CharField(choices=[('call', 'Звонок'), ('message', 'Сообщение'), ('two', 'Звонок+Сообщение')], default='call', max_length=20, verbose_name='Способ связи'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='heating',
            field=models.CharField(choices=[('electro', 'Электрическое'), ('gas', 'Газовое')], default='yes', max_length=20, verbose_name='Газ'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='payment',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('maternity', 'Мат. капитал'), ('mortgage', 'Ипотека'), ('military', 'Военная ипотека'), ('not', 'Неважно')], max_length=20, verbose_name='Варианты расчета'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='plane',
            field=models.CharField(choices=[('studio', 'Студия'), ('standart', 'Стандарт'), ('open', 'Свободная'), ('penthouse', 'Пентхаус')], default='open', max_length=20, verbose_name='Планировка'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='quantity',
            field=models.CharField(choices=[('1', '1-комнатная'), ('2', '2-комнатная'), ('3', '3-комнатная'), ('4', '4-комнатная')], default='1', max_length=20, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rejection',
            field=models.CharField(blank=True, choices=[('foto', 'Фото'), ('price', 'Цена'), ('description', 'Описание')], max_length=20, verbose_name='Причины отклонения'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='state',
            field=models.CharField(choices=[('need', 'Требует ремонта'), ('building', 'Ремонт от строителей')], default='building', max_length=20, verbose_name='Жилое состояние'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('rented', 'Сдан'), ('vacant', 'Не сдан')], default='rented', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='technology',
            field=models.CharField(choices=[('panel', 'Панельный'), ('monolith', 'Монолит')], default='panel', max_length=20, verbose_name='Технология'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='view',
            field=models.CharField(choices=[('secondary', 'Вторичное жилье'), ('primary', 'Новострой'), ('cottage', 'Коттедж')], default='primary', max_length=20, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='electricity',
            field=models.CharField(choices=[('yes', 'Подключено'), ('not', 'Отключено')], default='yes', max_length=20, verbose_name='Электричество'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='gas',
            field=models.CharField(choices=[('yes', 'Есть'), ('not', 'Нет')], default='yes', max_length=20, verbose_name='Газ'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='heating',
            field=models.CharField(choices=[('central', 'Центрайльное'), ('individual', 'Индивидуальное')], default='central', max_length=20, verbose_name='Отопление'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='sewage',
            field=models.CharField(choices=[('central', 'Центрайльное'), ('individual', 'Индивидуальное')], default='central', max_length=20, verbose_name='Каннализация'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='status',
            field=models.CharField(choices=[('apart', 'Квартира'), ('house', 'Дом')], default='apart', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='technology',
            field=models.CharField(choices=[('panel', 'Панельный'), ('monolith', 'Монолит')], default='panel', max_length=20, verbose_name='Технология'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='territory',
            field=models.CharField(choices=[('close', 'Закрытая'), ('open', 'Открытая')], default='close', max_length=20, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='view',
            field=models.CharField(choices=[('multifamily', 'многоквартирный'), ('singlefamily', 'одноквартирный')], default='singlefamily', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='watter_supply',
            field=models.CharField(choices=[('central', 'Центрайльное'), ('individual', 'Индивидуальное')], default='central', max_length=20, verbose_name='Водоснабжение'),
        ),
    ]
