# Generated by Django 3.2.19 on 2023-06-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='heating',
            new_name='apart_heating',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='state',
            new_name='apart_state',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='technology',
            new_name='apart_technology',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='view',
            new_name='apart_view',
        ),
        migrations.RenameField(
            model_name='infrastructure',
            old_name='heating',
            new_name='infrastructure_heating',
        ),
        migrations.RenameField(
            model_name='infrastructure',
            old_name='sewage',
            new_name='infrastructure_sewage',
        ),
        migrations.RenameField(
            model_name='infrastructure',
            old_name='view',
            new_name='infrastructure_view',
        ),
    ]
