# Generated by Django 3.2.19 on 2023-06-06 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infrastructures_app', '0003_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rejection',
            field=models.CharField(blank=True, choices=[('ok', 'Все ок'), ('foto', 'Фото'), ('price', 'Цена'), ('description', 'Описание')], max_length=20, verbose_name='Причины отклонения'),
        ),
    ]
