# Generated by Django 3.2.19 on 2023-06-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0004_auto_20230606_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='address',
            field=models.CharField(max_length=64, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='celling_height',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True, verbose_name='Высота потолков'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='distance',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Дистанция'),
        ),
    ]
