# Generated by Django 3.2.19 on 2023-06-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0005_auto_20230606_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='status',
            new_name='apart_status',
        ),
    ]
