# Generated by Django 3.2.19 on 2023-06-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0006_rename_status_apartment_apart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='heating',
            field=models.CharField(choices=[('electro_heating', 'Электрическое'), ('gas_heating', 'Газовое')], default='yes', max_length=20, verbose_name='Газ'),
        ),
    ]
