# Generated by Django 3.2.19 on 2023-06-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0007_alter_apartment_heating'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Главное фото'),
        ),
    ]
