# Generated by Django 3.2.19 on 2023-06-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0008_infrastructure_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='celling_height',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=10, verbose_name='Высота потолков'),
        ),
    ]
