# Generated by Django 3.2.19 on 2023-06-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0009_alter_infrastructure_celling_height'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='floors_id',
            new_name='floor_id',
        ),
    ]
