# Generated by Django 3.2.19 on 2023-06-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0010_rename_floors_id_apartment_floor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='Одобренно'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rejection',
            field=models.CharField(choices=[('foto', 'Фото'), ('price', 'Цена'), ('description', 'Описание')], default='', max_length=20, verbose_name='Причины отклонения'),
        ),
    ]
