# Generated by Django 3.2.19 on 2023-06-12 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion_app', '0005_promotion_activ'),
        ('infrastructures_app', '0011_auto_20230612_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='promotion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='promotion_app.promotion'),
        ),
    ]
