# Generated by Django 3.2.19 on 2023-06-12 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0012_alter_apartment_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageapart',
            name='apartment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageApart', to='infrastructures_app.apartment'),
        ),
    ]
