# Generated by Django 3.2.19 on 2023-06-12 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0013_alter_imageapart_apartment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='infrastructure_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageInfrastructure', to='infrastructures_app.infrastructure'),
        ),
    ]
