# Generated by Django 3.2.19 on 2023-06-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0014_alter_image_infrastructure_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apart_description',
            field=models.TextField(default='', max_length=400, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.DecimalField(decimal_places=1, default=25, max_digits=3, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='commission',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Коммисия агенту'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='kitchen_area',
            field=models.DecimalField(decimal_places=1, default=9, max_digits=3, verbose_name='Площадь кухни'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
