# Generated by Django 3.2.19 on 2023-06-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0015_auto_20230613_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corp',
            name='number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3, verbose_name='Корпус номер'),
        ),
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3, verbose_name='Секция номер'),
        ),
    ]
