# Generated by Django 3.2.19 on 2023-06-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0016_auto_20230613_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apart_description',
            field=models.TextField(max_length=400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='commission',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True, verbose_name='Коммисия агенту'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='kitchen_area',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Площадь кухни'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='celling_height',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True, verbose_name='Высота потолков'),
        ),
    ]
