# Generated by Django 3.2.19 on 2023-06-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0018_apartment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='image_place',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='img/image/'),
        ),
    ]
