# Generated by Django 3.2.19 on 2023-06-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0019_auto_20230614_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_place',
            field=models.IntegerField(null=True),
        ),
    ]
