# Generated by Django 3.2.19 on 2023-06-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0020_alter_image_image_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='hash',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
