# Generated by Django 3.2.19 on 2023-06-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0022_remove_image_image_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageapart',
            name='image_place',
            field=models.IntegerField(null=True),
        ),
    ]
