# Generated by Django 3.2.19 on 2023-06-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures_app', '0023_imageapart_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='state',
            field=models.CharField(choices=[('need', 'Требует ремонта'), ('building', 'Ремонт от строителей')], default='building', max_length=30, verbose_name='Жилое состояние'),
        ),
    ]
