# Generated by Django 4.2.1 on 2023-05-27 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=400, verbose_name='Добавить фразу')),
                ('highlight', models.CharField(max_length=10, verbose_name='Добавить цвет')),
                ('big', models.BooleanField(default=False, verbose_name='Большое')),
                ('raise_up', models.BooleanField(default=False, verbose_name='Поднять')),
                ('turbo', models.BooleanField(default=False, verbose_name='Турбо')),
                ('date', models.DateTimeField(default=datetime.date.today, verbose_name='Дата')),
                ('payday', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Цена')),
            ],
        ),
    ]
