# Generated by Django 3.2.19 on 2023-06-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion_app', '0003_alter_promotion_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='phrase',
            field=models.CharField(choices=[('1', 'Подарок при покупке'), ('2', 'Возможет торг'), ('3', 'Квартира у моря'), ('4', 'В спальном районе'), ('5', 'Вам повезло с ценой'), ('6', 'Для большой семьй'), ('7', 'Семейное гнездышко'), ('8', 'Отдельная парковка')], default='', max_length=400, verbose_name='Добавить фразу'),
        ),
    ]
