# Generated by Django 3.2.19 on 2023-06-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion_app', '0006_alter_promotion_payday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='payday',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Цена'),
        ),
    ]
